# Generated by Django 2.2 on 2020-02-09 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('reg_id', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('ARCHITECTURE', 'ARCHITECTURE'), ('PHARMACY', 'PHARMACY'), ('ENGLISH', 'ENGLISH'), ('BBA', 'BBA')], max_length=20)),
                ('profile_pic', models.ImageField(blank=True, default='default.png', upload_to='', verbose_name='profile_pics/')),
                ('cell_number', models.CharField(blank=True, max_length=12, null=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last_login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='promo_pic/')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField(default='Something about your post...', max_length=200)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Job', 'Job'), ('Service/Volunteer', 'Service/Volunteer'), ('Accommodation', 'Accommodation'), ('Tuition', 'Tuition'), ('Borrow', 'Borrow'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=20)),
                ('image1', models.ImageField(upload_to='ans_images')),
                ('image2', models.ImageField(blank=True, default='default2.png', upload_to='ans_images')),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
