# Generated by Django 2.2 on 2020-02-07 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('reg_id', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('ARCHITECTURE', 'ARCHITECTURE'), ('PHARMACY', 'PHARMACY'), ('ENGLISH', 'ENGLISH'), ('BBA', 'BBA')], max_length=20)),
                ('profile_pic', models.ImageField(blank=True, upload_to='', verbose_name='profile_pics/')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last_login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_c', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('Civil', 'Civil'), ('Architecture', 'Architecture'), ('Pharmacy', 'Pharmacy'), ('English', 'English'), ('Business', 'Business'), ('Law', 'Law'), ('History', 'History'), ('Math', 'Math'), ('Others', 'Others'), ('Mobile', 'Mobile'), ('Mobile Accessories', 'Mobile Accessories'), ('Computer & laptop', 'Computer & laptop'), ('Computer & laptop Accessories', 'Computer & laptop Accessories'), ('Camera & Camera Accessories', 'Camera & Camera Accessories'), ('Other Electronics', 'Other Electronics'), ('Business', 'Business')], max_length=55, null=True)),
                ('main_c', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Books', 'Books'), ('Job', 'Job'), ('Service/Volunteer', 'Service/Volunteer'), ('Accommodation', 'Accommodation'), ('Tution', 'Tution'), ('Borrow', 'Borrow'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='promo_pic/')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=6)),
                ('description', models.TextField(default='', max_length=200)),
                ('image1', models.ImageField(blank=True, default='images/demo.jpg', null=True, upload_to='PostAD_pic/')),
                ('image2', models.ImageField(blank=True, default='images/demo.jpg', null=True, upload_to='PostAD_pic/')),
                ('date_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('cat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Categories')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
