# Generated by Django 2.2 on 2020-02-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=20)),
                ('image', models.ImageField(upload_to='promo_pic/')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
            ],
        ),
    ]
