# Generated by Django 2.2 on 2020-02-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='profile_pics/'),
        ),
    ]
