# Generated by Django 2.2 on 2020-02-06 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200206_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=6)),
                ('description', models.TextField(default='', max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='PostAD_pic/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='PostAD_pic/')),
                ('date_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='promo',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
