# Generated by Django 2.2 on 2020-02-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200208_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='contact',
            field=models.CharField(default='', max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postad',
            name='cat_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postad',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
