# Generated by Django 2.2 on 2020-02-07 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200206_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postad',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='contact',
        ),
        migrations.AddField(
            model_name='postad',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postad',
            name='image1',
            field=models.ImageField(blank=True, default='images/demo.jpg', null=True, upload_to='PostAD_pic/'),
        ),
        migrations.AlterField(
            model_name='postad',
            name='image2',
            field=models.ImageField(blank=True, default='images/demo.jpg', null=True, upload_to='PostAD_pic/'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.CharField(max_length=50)),
                ('main_cat', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.PostAd')),
            ],
        ),
    ]
