# Generated by Django 2.2 on 2020-02-03 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import question_bank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('question_type', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('semester', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=question_bank.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
