# Generated by Django 2.2 on 2020-02-08 10:29

from django.db import migrations, models
import question_bank.models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_auto_20200208_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image2',
            field=models.ImageField(blank=True, default='default2.png', upload_to='ans_images'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image3',
            field=models.ImageField(blank=True, default='default2.png', upload_to='ans_images'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image4',
            field=models.ImageField(blank=True, default='default2.png', upload_to='ans_images'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image5',
            field=models.ImageField(blank=True, default='default2.png', upload_to='ans_images'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image6',
            field=models.ImageField(blank=True, default='default2.png', upload_to='ans_images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image2',
            field=models.ImageField(blank=True, default='default2.png', upload_to=question_bank.models.upload_location),
        ),
        migrations.AlterField(
            model_name='question',
            name='image3',
            field=models.ImageField(blank=True, default='default2.png', upload_to=question_bank.models.upload_location),
        ),
        migrations.AlterField(
            model_name='question',
            name='image4',
            field=models.ImageField(blank=True, default='default2.png', upload_to=question_bank.models.upload_location),
        ),
        migrations.AlterField(
            model_name='question',
            name='image5',
            field=models.ImageField(blank=True, default='default2.png', upload_to=question_bank.models.upload_location),
        ),
    ]
